name: Auto-publish

on: [push, workflow_dispatch]

jobs:
  # Auto-publish when version is increased
  publish-job:
    # Only publish on `main` branch
    runs-on: ubuntu-latest
    permissions:  # Don't forget permissions
      contents: write

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Fail if changelog not updated
      run: if [ -z $(git diff --name-only $(git describe --tags --abbrev=0) | grep CHANGELOG.md) ]; then exit 1; fi
